version: "3.2"

services:

  # rosalind:    
  #   image: rosalind:1.0.0
  #   ports:      
  #     - "80:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     net_platform:
  #       ipv4_address: 172.28.0.3

  db:
    image: mysql:5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: sqlname
      MYSQL_PASSWORD: sqlpassword
      MYSQL_DATABASE: sqldb
    networks:
      net_platform:
        ipv4_address: 172.28.0.2

    volumes:
      - type: "volume"
        source: "db-volume"
        target: "/var/lib/mysql" # persistent DB
      - ./custom-sql-options/:/etc/mysql/conf.d

volumes:
  db-volume:

networks:
  net_platform:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
